version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'pgdb:/var/lib/postgresql/data'
    networks:
      - passin
  
  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - API_BASE_URL=${API_BASE_URL}:${PORT}
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  pgdb: